baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Johanna Flasshaar'
theme = 'smol'

copyright = "© Johanna Flasshaar"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Collections"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/johannalockw/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Inspiration"
url = "/inspiration/"
weight = 3
